apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-nodejs
  namespace: default
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/karthik_jk/devfile-nodejs
        name: container-image
        resources: {}
status: {}
